version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main

jobs:
  build:
    working_directory: ~/Source-Code
    docker:
      - image: cimg/node:20.14.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: |
            CI=true npm test -- --watchAll=false --passWithNoTests
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths: .

  deploy:
    working_directory: ~/Source-Code
    docker:
      - image: cimg/node:20.14.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Setup SSH
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/ec2_key
            chmod 600 ~/.ssh/ec2_key
            ssh-keyscan $EC2_PUBLIC_DNS >> ~/.ssh/known_hosts
      - run:
          name: Create deployment script
          command: |
            # Create script line by line
            echo '#!/usr/bin/env bash' > deploy.sh
            echo 'set -e' >> deploy.sh
            echo 'sudo apt-get update' >> deploy.sh
            echo 'if ! command -v node &>/dev/null; then' >> deploy.sh
            echo '  curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -' >> deploy.sh
            echo '  sudo apt-get install -y nodejs nginx' >> deploy.sh
            echo '  sudo npm install -g npm@latest pm2' >> deploy.sh
            echo 'fi' >> deploy.sh
            echo 'rm -rf Source-Code' >> deploy.sh
            echo 'git clone https://github.com/GroupA-DevOpsSec-2025/Source-Code.git' >> deploy.sh
            echo 'cd Source-Code' >> deploy.sh
            echo 'npm install' >> deploy.sh
            echo 'npm run build' >> deploy.sh
            echo 'sudo rm -rf /var/www/html/*' >> deploy.sh
            echo 'sudo cp -a build/* /var/www/html/' >> deploy.sh
            echo 'sudo chown -R www-data:www-data /var/www/html' >> deploy.sh
            
            # Add Nginx config with HTTPS support
            echo "echo 'server {" > nginx-config.sh
            echo "  listen 80;" >> nginx-config.sh
            echo "  server_name \$EC2_PUBLIC_DNS;" >> nginx-config.sh
            echo "  # Redirect all HTTP requests to HTTPS" >> nginx-config.sh
            echo "  return 301 https://\$host\$request_uri;" >> nginx-config.sh
            echo "}" >> nginx-config.sh
            echo "" >> nginx-config.sh
            echo "server {" >> nginx-config.sh
            echo "  listen 443 ssl;" >> nginx-config.sh
            echo "  server_name \$EC2_PUBLIC_DNS;" >> nginx-config.sh
            echo "  # SSL certificate configuration" >> nginx-config.sh
            echo "  ssl_certificate /etc/ssl/certs/server.crt;" >> nginx-config.sh
            echo "  ssl_certificate_key /etc/ssl/private/privatekey.pem;" >> nginx-config.sh
            echo "" >> nginx-config.sh
            echo "  root /var/www/html;" >> nginx-config.sh
            echo "  location / {" >> nginx-config.sh
            echo "    try_files \$uri /index.html;" >> nginx-config.sh
            echo "  }" >> nginx-config.sh
            echo "  # API proxy configuration" >> nginx-config.sh
            echo "  location /api {" >> nginx-config.sh
            echo "    proxy_pass http://localhost:3001;" >> nginx-config.sh
            echo "    proxy_http_version 1.1;" >> nginx-config.sh
            echo "    proxy_set_header Upgrade \$http_upgrade;" >> nginx-config.sh
            echo "    proxy_set_header Connection \"upgrade\";" >> nginx-config.sh
            echo "    proxy_set_header Host \$host;" >> nginx-config.sh
            echo "    proxy_set_header X-Real-IP \$remote_addr;" >> nginx-config.sh
            echo "    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;" >> nginx-config.sh
            echo "  }" >> nginx-config.sh
            echo "}' | sudo tee /etc/nginx/sites-available/todo-app >/dev/null" >> nginx-config.sh
            
            # Add SSL certificate setup script
            echo 'echo "-----BEGIN PRIVATE KEY-----"' > ssl-setup.sh
            echo 'echo "$PRIVATE_KEY"' >> ssl-setup.sh
            echo 'echo "-----END PRIVATE KEY-----"' >> ssl-setup.sh
            echo 'echo "-----BEGIN CERTIFICATE-----"' >> ssl-setup.sh
            echo 'echo "$SERVER_CERT"' >> ssl-setup.sh
            echo 'echo "-----END CERTIFICATE-----"' >> ssl-setup.sh
            
            echo '# Create SSL directories and install certificates' >> deploy.sh
            echo 'sudo mkdir -p /etc/ssl/private /etc/ssl/certs' >> deploy.sh
            echo 'chmod +x ssl-setup.sh' >> deploy.sh
            echo '# Install private key' >> deploy.sh
            echo './ssl-setup.sh | sudo tee /etc/ssl/private/privatekey.pem >/dev/null' >> deploy.sh
            echo '# Install server certificate' >> deploy.sh
            echo './ssl-setup.sh | sudo tee /etc/ssl/certs/server.crt >/dev/null' >> deploy.sh
            
            echo '# Finalize Nginx configuration' >> deploy.sh
            echo 'chmod +x nginx-config.sh' >> deploy.sh
            echo './nginx-config.sh' >> deploy.sh
            echo 'sudo ln -sf /etc/nginx/sites-available/todo-app /etc/nginx/sites-enabled/' >> deploy.sh
            echo 'sudo rm -f /etc/nginx/sites-enabled/default' >> deploy.sh
            echo '# Start server application' >> deploy.sh
            echo 'cd server' >> deploy.sh
            echo 'npm install' >> deploy.sh
            echo 'pm2 delete todo-api 2>/dev/null || true' >> deploy.sh
            echo 'pm2 start ./bin/www --name todo-api' >> deploy.sh
            echo 'pm2 save' >> deploy.sh
            echo 'pm2 startup || true' >> deploy.sh
            echo '# Restart Nginx' >> deploy.sh
            echo 'sudo nginx -t && sudo systemctl restart nginx' >> deploy.sh
            
            chmod +x deploy.sh
      - run:
          name: Deploy application
          command: |
            scp -i ~/.ssh/ec2_key deploy.sh $EC2_USERNAME@$EC2_PUBLIC_DNS:~
            ssh -i ~/.ssh/ec2_key -o StrictHostKeyChecking=no \
              $EC2_USERNAME@$EC2_PUBLIC_DNS \
              "export EC2_PUBLIC_DNS='$EC2_PUBLIC_DNS'; export PRIVATE_KEY='$PRIVATE_KEY'; export SERVER_CERT='$SERVER_CERT'; bash ~/deploy.sh"