version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main

jobs:
  build:
    working_directory: ~/Source-Code
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm test
      - persist_to_workspace:
          root: .
          paths: .

  deploy:
    working_directory: ~/Source-Code
    docker:
      - image: cimg/node:16.14.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build application
          command: npm run build
      - run:
          name: Create deployment package
          command: tar -czf deploy.tar.gz build/ server/
      - run:
          name: Generate Nginx config
          command: |
            echo 'server {
              listen 80;
              server_name _;
              root /home/ubuntu/Source-Code/build;
              
              location / {
                try_files \$uri /index.html;
              }
              
              location /api {
                proxy_pass http://localhost:3001;
                proxy_http_version 1.1;
                proxy_set_header Upgrade \$http_upgrade;
                proxy_set_header Connection "upgrade";
              }
            }' > nginx-config
      - run:
          name: Transfer files to EC2
          command: scp -o StrictHostKeyChecking=no deploy.tar.gz nginx-config $EC2_USERNAME@$EC2_PUBLIC_DNS:/tmp/
      - run:
          name: Execute deployment commands
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "\
              command -v node >/dev/null 2>&1 || {\
                curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash - ;\
                sudo apt-get install -y nodejs nginx ;\
                sudo npm install -g pm2 ;\
              } ;\
              rm -rf ~/Source-Code ;\
              mkdir -p ~/Source-Code ;\
              tar -xzf /tmp/deploy.tar.gz -C ~/Source-Code ;\
              sudo mv /tmp/nginx-config /etc/nginx/sites-available/todo-app ;\
              sudo ln -sf /etc/nginx/sites-available/todo-app /etc/nginx/sites-enabled ;\
              sudo nginx -t && sudo systemctl restart nginx ;\
              cd ~/Source-Code/server && npm install --production ;\
              pm2 delete todo-api 2>/dev/null || true ;\
              pm2 start index.js --name todo-api ;\
              pm2 save"